## Travis CI configuration for the pytest-cgi plugin.
##
##   <https://travis-ci.org/mdklatt/pytest-cgi>
##
language: python

python:
  - "3.6"
  - "3.7-dev"

branches:
  only:
    - master
    - dev

sudo: false

install:
  - python -m pip install -r requirements.txt -e .

script:
  - python -m pytest --verbose test/
